name = "BandedMatrices"
uuid = "aae01518-5342-5314-be14-df237901396f"
version = "0.15.15"


[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArrayLayouts = "0.4"
FillArrays = "0.9.1"
julia = "1"

[extras]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"

[targets]
test = ["Base64", "Test", "GenericLinearAlgebra"]
